name: Build Web Client
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: cd flutter/web/js && npm install ts-proto && npm install vite@2.8 && npm install yarn -g && npm install typescript -g && npm install protoc -g && yarn build

      - name: Building Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          # 下方的name格式为：Docker Hub ID/自定义镜像名称
          name: iyserver/rustdesk-web
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
          workdir: './flutter'
