name: Build Web Client
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Prepare Environment 
        run: |
          apt-get update && apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3 clang cmake ninja-build pkg-config libgtk-3-dev
          cd flutter/web/js && npm install ts-proto && npm install vite@2.8 && npm install yarn -g && npm install typescript -g && npm install protoc -g && yarn build
          sudo git clone https://github.com/flutter/flutter.git /usr/local/flutter
    
      - name: Setting Flutter
        env:
          PATH: "/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:$PATH"
        run: |
          cd flutter && flutter doctor
          flutter channel master
          flutter config --enable-web
          flutter build web
          tar -czf ../web.tar.gz flutter/build/web

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: web.tar.gz
    
